
---
spring:
  config:
    activate:
      on-profile: default
  sql:
    init:
      platform: h2
cds:
  data-source:
    auto-config:
      enabled: false
  remote:
    services:
      '[CustomerService]':
        destination:
          name: service-provider-srv
        type: odata-v4
        http:
          suffix: /odata/v4

---
spring:
  config:
    activate:
      on-profile: hybrid
cds:
  data-source:
    auto-config:
      enabled: false
  remote:
    services:
      '[CustomerService]':
        destination:
          name: service-provider-srv
        type: odata-v4
        http:
          suffix: /odata/v4
---
spring:
  config:
    activate:
      on-profile: cloud
cds:
  data-source:
    auto-config:
      enabled: false
  remote:
    services:
      '[CustomerService]':
        destination:
          name: service-provider-srv
          # tokenExchangeStrategy: ExchangeOnly
          # retrievalStrategy: AlwaysSubscriber
        type: odata-v4
        http:
          suffix: /odata/v4
  security:
    authentication:
      normalizeProviderTenant: false

logging:
  level:
    com.sap.cloud.sdk: DEBUG
    com.sap.cds: DEBUG          
---
management:
  endpoint:
    health:
      show-components: always
      probes.enabled: true
  endpoints:
    web:
      exposure:
        include: health
  health:
    defaults.enabled: false
    ping.enabled: true
    db.enabled: true
